/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DInN_aliases.h"
#include "DInN.h"
#include "Comp_2.h"
#include "Vout_1_aliases.h"
#include "Vout_1.h"
#include "DInP_aliases.h"
#include "DInP.h"
#include "Comp_1.h"
#include "VDAC8_1.h"
#include "Opamp_1.h"
#include "TransmitWordShift.h"
#include "BitCounterEnc.h"
#include "StartTransmit.h"
#include "Waiter.h"
#include "Clock_2.h"
#include "BitCounterDec.h"
#include "RecieveShiftReg.h"
#include "Sh_isr_aliases.h"
#include "Sh_isr.h"
#include "WordShifted.h"
#include "TransmitShiftReg.h"
#include "Clock_1.h"
#include "isr_Load_TrShReg.h"
#include "FrameAllow.h"
#include "StartButton.h"
#include "Start_aliases.h"
#include "Start.h"
#include "Clock_3.h"
#include "BitCounterDec_comp_aliases.h"
#include "BitCounterDec_comp.h"
#include "Sh_in_aliases.h"
#include "Sh_in.h"
#include "BitCounter_in_aliases.h"
#include "BitCounter_in.h"
#include "Data_in_aliases.h"
#include "Data_in.h"
#include "DIn1N_aliases.h"
#include "DIn1N.h"
#include "DIn1P_aliases.h"
#include "DIn1P.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Pin_4_aliases.h"
#include "Pin_4.h"
#include "Clock_4.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

