/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DInN_aliases.h"
#include "DInN.h"
#include "Comp_2.h"
#include "Vout_1_aliases.h"
#include "Vout_1.h"
#include "DInP_aliases.h"
#include "DInP.h"
#include "Comp_1.h"
#include "VDAC8_1.h"
#include "Opamp_1.h"
#include "FrameAllow.h"
#include "Waiter.h"
#include "Clock_2.h"
#include "BitCounterDec.h"
#include "RecieveShiftReg.h"
#include "WordShifted.h"
#include "TransmitShiftReg.h"
#include "TransmitWordShift.h"
#include "isr_Load_TrShReg.h"
#include "StartTransmit.h"
#include "BitCounterEnc.h"
#include "Clock_5.h"
#include "EndFrame.h"
#include "StartButton_1.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "Counter_1.h"
#include "isr_update_time.h"
#include "S1ms_aliases.h"
#include "S1ms.h"
#include "Clock_10.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

